--- 
abstract: Machine-readable Changes file
author: 
  - Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Changes
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  Class::Factory::Enhanced: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  Getopt::Attribute: 0
  Perl::Version: 0
  YAML: 0
  perl: 5.6.0
version: 0.03
